version: '3'
volumes:
  postgres:
  node_modules:
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=databas3 # only for local
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
  web:
    image: wonka-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rails server --port=5000 --binding=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  css:
    image: wonka-web
    depends_on:
      - web
    command: yarn build:css --watch
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
  js:
    image: wonka-web
    depends_on:
      - web
    command: yarn build --watch
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
